title: "Feisi Fu"
author: "Feisi Fu"
description: "Links"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true          # adds a gray frame to the site
show_sidebar: false       # show a sidebar instead of the usual header
minimal: false            # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "CV", url: "/FeisiFuCV.pdf"}
  - {file: "publications.md", title: "Publications"}
  - {file: "updates.md", title: "News"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: "Email: fufeisi2023@gmail.com", url: "mailto:fufeisi2023@gmail.com"}
  - {title: "Phone: 857-869-0444", url: "tel:+18578690444"}
  - {title: LinkedIn, url: "https://www.linkedin.com/in/feisifu/"}
  - {title: Google Scholar, url: "https://scholar.google.com/citations?user=9wJGIOoAAAAJ"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
